name: megenagna_mobile
description: "Project Megenagna Mobile App for iOS and Android - Offline Pinpoint Addressing for Ethiopia"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
